import {
  AlarmClock,
  Baby,
  Backpack,
  Bath,
  BedDouble,
  BookHeart,
  BookOpen,
  ChefHat,
  ClipboardList,
  Dog,
  Droplets,
  Footprints,
  Fuel,
  GraduationCap,
  Hammer,
  Handshake,
  HeartHandshake,
  Home,
  Heart,
  Medal,
  Moon,
  PencilLine,
  PhoneOff,
  School,
  ShieldCheck,
  Shirt,
  SmilePlus,
  Soup,
  Sparkles,
  Star,
  Target,
  Trash2,
  Trees,
  Utensils,
  Wallet,
  WashingMachine,
  Wind,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

/** Icon per catalog act, keyed by the id after the band prefix. Display only. */
const ICONS: Record<string, LucideIcon> = {
  'make-bed': BedDouble,
  'pack-backpack': Backpack,
  dogs: Dog,
  'dogs-feed': Dog,
  'dogs-water': Droplets,
  'parents-room': Heart,
  'unload-dishwasher': Utensils,
  'vacuum-living': Wind,
  trash: Trash2,
  balcony: Trees,
  'wake-on-time': AlarmClock,
  'room-clean': Sparkles,
  closet: Shirt,
  'kids-outside': Trees,
  'read-30': BookOpen,
  'test-90': Medal,
  'ready-school': School,
  'ready-bed': Moon,
  honest: ShieldCheck,
  'read-20': BookOpen,
  'homework-calm': PencilLine,
  'school-growth': GraduationCap,
  'help-food': Utensils,
  'room-reset': Sparkles,
  'room-keep': Home,
  teeth: SmilePlus,
  'shoes-coat-door': Footprints,
  hamper: Shirt,
  'kind-sibling': HeartHandshake,
  'shoes-first-ask': Footprints,
  'bible-verse': BookHeart,
  laundry: WashingMachine,
  'trash-recycle': Trash2,
  'kitchen-dinner': ChefHat,
  'solo-meal': Soup,
  bathroom: Bath,
  'watch-kids': Baby,
  'homework-no-reminders': PencilLine,
  'alarm-ready': AlarmClock,
  'follow-through': Target,
  'own-mistake': Handshake,
  'adult-skill': Wrench,
  'teach-little': GraduationCap,
  'fill-gas': Fuel,
  'meal-plan': ClipboardList,
  'budget-errand': Wallet,
  'no-phone-focus': PhoneOff,
  'small-fix': Hammer,
  'own-trash-day': Trash2,
  'help-fil': HeartHandshake,
  'caught-good': Star,
  'outstanding-day': Medal,
}

export function actIcon(actId: string): LucideIcon {
  const key = actId
    .slice(actId.indexOf('.') + 1)
    .replace(/-(little|teen)$/, '')
  return ICONS[key] ?? Sparkles
}
